import { z } from "zod";

const schema = z.object({
  NEXT_PUBLIC_APP_URL: z.string().url().default("http://localhost:3000"),
  DATABASE_URL: z.string().optional(),
  NEON_DATABASE_URL: z.string().optional(),
  EXECUTION_MODE: z.enum(["mock", "remote-http"]).default("mock"),
  RUNTIME_CONTROLLER_URL: z.string().url().optional(),
  RUNTIME_CONTROLLER_TOKEN: z.string().optional(),
  RUNTIME_CALLBACK_TOKEN: z.string().default("dev-runtime-token"),
  RUNTIME_STATUS_CALLBACK_URL: z.string().url().optional(),
  OPENCLAW_RUNTIME_IMAGE: z.string().default("ghcr.io/openclaw/openclaw:latest"),
  // Payment providers: only one is active at a time, but we keep configs for easy switching.
  // Dodo Payments (preferred when configured)
  DODO_PAYMENTS_API_KEY: z.string().optional(),
  DODO_PAYMENTS_ENV: z.enum(["test", "live"]).default("test"),
  // Dodo uses Standard Webhooks; secret is base64-encoded.
  DODO_PAYMENTS_WEBHOOK_SECRET: z.string().optional(),
  DODO_PRODUCT_STARTER_MONTHLY: z.string().optional(),
  DODO_PRODUCT_STARTER_YEARLY: z.string().optional(),
  DODO_PRODUCT_PRO_MONTHLY: z.string().optional(),
  DODO_PRODUCT_PRO_YEARLY: z.string().optional(),
  DODO_BILLING_CURRENCY: z.string().default("USD"),
  PAYPAL_CLIENT_ID: z.string().optional(),
  PAYPAL_CLIENT_SECRET: z.string().optional(),
  PAYPAL_ENV: z.enum(["sandbox", "live"]).default("sandbox"),
  PAYPAL_WEBHOOK_ID: z.string().optional(),
  PAYPAL_PLAN_STARTER_MONTHLY: z.string().optional(),
  PAYPAL_PLAN_STARTER_YEARLY: z.string().optional(),
  PAYPAL_PLAN_PRO_MONTHLY: z.string().optional(),
  PAYPAL_PLAN_PRO_YEARLY: z.string().optional(),
  RAZORPAY_KEY_ID: z.string().optional(),
  RAZORPAY_KEY_SECRET: z.string().optional(),
  RAZORPAY_WEBHOOK_SECRET: z.string().optional(),
  RAZORPAY_PLAN_STARTER_MONTHLY: z.string().optional(),
  RAZORPAY_PLAN_STARTER_YEARLY: z.string().optional(),
  RAZORPAY_PLAN_PRO_MONTHLY: z.string().optional(),
  RAZORPAY_PLAN_PRO_YEARLY: z.string().optional(),
  RAZORPAY_CURRENCY: z.string().default("INR"),
  RAZORPAY_TEST_MODE: z.enum(["0", "1"]).default("0"),
  ENCRYPTION_KEY: z.string().min(16).default("dev-only-change-me"),
  WARM_POOL_SIZE: z.coerce.number().int().positive().default(5),
  PLATFORM_OPENROUTER_API_KEY: z.string().optional(),
  BRAND_CONTENT_MODEL: z.string().default("openai/gpt-5.2"),
  BRAND_RESEARCH_PIPELINE_ENABLED: z.enum(["0", "1"]).default("1"),
  RESEARCH_CRAWLER_ENGINE: z.enum(["adaptive", "cheerio", "playwright", "crawlee", "basic"]).default("adaptive"),
  RESEARCH_ENABLE_GUESS_PATHS: z.enum(["0", "1"]).default("0"),
  OPENROUTER_PROVISIONING_KEY: z.string().optional(),
  OPENROUTER_PROVISIONING_LIMIT_USD: z.coerce.number().positive().default(10),
  X_CLIENT_ID: z.string().optional(),
  X_CLIENT_SECRET: z.string().optional(),
  X_REDIRECT_URI: z.string().url().optional(),
  X_OAUTH_SCOPES: z.string().default("tweet.read tweet.write users.read offline.access"),
  INTERNAL_BOT_TOKEN: z.string().optional(),
  X_POST_COOLDOWN_MINUTES: z.coerce.number().int().positive().default(60),
  X_REPLY_COOLDOWN_MINUTES: z.coerce.number().int().positive().default(3),
  X_CONTENT_DEDUPE_WINDOW_HOURS: z.coerce.number().int().positive().default(24),
  X_REPLY_THREAD_USER_LIMIT: z.coerce.number().int().positive().default(1)
});

export const env = schema.parse(process.env);
